name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cuda-toolkit=12.4
  - plyfile
  - python=3.12.7
  - pip=24.3.1
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pytorch-cuda=12.4
  - opencv-python
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn